routes/web.php
<?php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        Route::post('logout', 'LoginController@logout')->name('logout');
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('socialite/{provider}', 'AuthController@redirectToProvider');
        Route::get('socialite/{provider}/callback', 'AuthController@handleProviderCallback');
    });
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'roles'], 'block' => ['null']], function () {
        Route::group(['roles' => ['User', 'Author', 'Moderator', 'Admin']], function () {
            Route::get('/', 'AdminController@index')->name('admin.index');
            Route::get('profile', 'ProfileController@index')->name('profile.index');
            Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
            Route::put('profile/{id}/edit', 'ProfileController@updateedit');
            Route::get('profile/{id}/password', 'ProfileController@password')->name('profile.password');
            Route::put('profile/{id}/password', 'ProfileController@updatepassword');
            Route::delete('profile/{id}', 'ProfileController@destroy')->name('profile.destroy');
            Route::resource('urls', 'UrlController');
        });
        Route::group(['roles' => ['Admin']], function () {
            Route::resource('users', 'UserController');
            Route::get('roles', 'RoleController@index')->name('roles.index');
            Route::get('role/{id}', 'RoleController@show')->name('roles.show');
            Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
            Route::put('roles/{id}', 'RoleController@update')->name('roles.update');
            Route::get('settings', 'AdminController@settings')->name('admin.settings');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('admin.logs');
        });
    });
    Route::namespace('Site')->group(function () {
        Route::get('/', 'SiteController@index')->name('site.index');
        Route::put('/', 'SiteController@submit');
        Route::get('anonymous/{id}', 'SiteController@anonymous')->name('site.anonymous')->where('id', '[\w\d\-\_]+');
        Route::get('url/{id}', 'SiteController@url')->name('site.url')->where('id', '[\w\d\-\_]+');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    protected $fillable = ['name', 'email', 'password', 'github_id', 'google_id', 'facebook_id', 'twitter_id', 'role_id',];
    protected $hidden = ['password', 'remember_token',];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use App\Http\Requests\User as Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $main = User::all();
        return view('admin.users.index', compact('main'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $role = Role::all();
        return view('admin.users.create', compact('role'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role_id' => $request->role_id
        ]);
        return redirect()->route('users.index')->with('success', __('admin.created-success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $main = User::find($id);
        return view('admin.users.show', compact('main'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::all();
        $main = User::find($id);
        return view('admin.users.edit', compact('main', 'role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        User::find($id)->update([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'role_id' => $request->role_id
        ]);
        return redirect()->route('users.index')->with('success', __('admin.updated-success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        User::find($id)->delete();
        return redirect()->route('users.index')->with('success', __('admin.information-deleted'));
    }
}

resources/views/ru/admin/users/create.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.create-users'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('users.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label>{{ __('admin.users-name') }}</label>
            <input type="text" class="form-control" name="name" value="{{ old('name') }}"
                   placeholder="{{ __('admin.users-enter-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-name') }}</label>
            <input type="email" class="form-control" name="email" value="{{ old('email') }}"
                   placeholder="{{ __('admin.users-enter-email') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-password') }}</label>
            <input type="password" class="form-control" name="password"
                   {{ old('password') }} placeholder="{{ __('admin.users-enter-password') }}"
                   required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-roles') }}</label>
            <select class="form-control" name="role_id" required>
                @foreach($role as $item)
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.create') }}</button>
    </form>
@endsection

resources/views/ru/admin/users/edit.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.edit-users'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('users.update',$main->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label>{{ __('admin.users-name') }}</label>
            <input type="text" class="form-control" name="name" value="{{ $main->name }}"
                   placeholder="{{ __('admin.users-enter-name') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-email') }}</label>
            <input type="email" class="form-control" name="email" value="{{ $main->email }}"
                   placeholder="{{ __('admin.users-enter-email') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-password') }}</label>
            <input type="password" class="form-control" name="password" value="{{ $main->password }}"
                   placeholder="{{ __('admin.users-enter-password') }}" required>
        </div>

        <div class="form-group">
            <label>{{ __('admin.users-roles') }}</label>
            <select class="form-control" name="role_id" required>
                <option value="{{ $main->role->id }}">{{ $main->role->name }}</option>
                @foreach($role as $item)
                    @if($main->role->id === $item->id) @continue; @endif
                    <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.edit') }}</button>
    </form>
@endsection

resources/views/ru/admin/users/index.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.users'))

@section('content')
    <div class="row justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="col-lg-9">
            <div class="d-flex">
                <h1 class="h2">@yield('title')</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="pull-right">
                <a class="btn btn-original" href="{{ route('users.create') }}">{{ __('admin.create-users') }}</a>
            </div>
        </div>
    </div>
    @include('admin.includes.success')
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th scope="col">{{ __('admin.users-id') }}</th>
                <th scope="col">{{ __('admin.users-name') }}</th>
                <th scope="col">{{ __('admin.users-email') }}</th>
                <th scope="col">{{ __('admin.users-password') }}</th>
                <th scope="col">{{ __('admin.users-gitHub') }}</th>
                <th scope="col">{{ __('admin.users-google') }}</th>
                <th scope="col">{{ __('admin.users-facebook') }}</th>
                <th scope="col">{{ __('admin.users-twitter') }}</th>
                <th scope="col">{{ __('admin.users-roles') }}</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($main as $item)
                <tr>
                    <th scope="row">{{ $item->id }}</th>
                    <td scope="row">{{ $item->name }}</td>
                    <td scope="row">{{ $item->email }}</td>
                    <td scope="row">
                        @if($item->password)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->github_id)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->google_id)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->facebook_id)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        @if($item->twitter_id)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        {{ $item->role->name }}
                    </td>
                    <td scope="row">
                        <a href="{{ route('users.show',$item->id) }}"><i class="far fa-eye"></i></a>
                        <a href="{{ route('users.edit',$item->id) }}"><i class="fas fa-edit"></i></a>
                        <form action="{{ route('users.destroy',$item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/ru/admin/users/show.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.show-users'))

@section('content')
    @include('admin.includes.title')
    <ul class="nav mb-md-3">
        <li>
            <a href="{{ route('users.index') }}" class="btn btn-dark">{{ __('admin.back') }}</a>
            <a href="{{ route('users.edit', $main->id) }}" class="btn btn-primary">{{ __('admin.update') }}</a>
            <form action="{{ route('users.destroy', $main->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">{{ __('admin.delete') }}</button>
            </form>
        </li>
    </ul>
    <table class="table">
        <tr>
            <th>{{ __('admin.users-id') }}</th>
            <td>{{ $main->id }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.users-name') }}</th>
            <td>{{ $main->name }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.users-email') }}</th>
            <td>{{ $main->email }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.users-password') }}</th>
            <td>
                @if( $main->password )
                    {{ $main->password }}
                @else
                    {{ __('admin.disabled') }}
                @endif</td>
        </tr>
        <tr>
            <th>{{ __('admin.users-gitHub') }}</th>
            <td>
                @if( $main->github_id )
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.users-google') }}</th>
            <td>
                @if( $main->google_id )
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.users-facebook') }}</th>
            <td>
                @if( $main->facebook_id )
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.users-twitter') }}</th>
            <td>
                @if( $main->twitter_id )
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
        <tr>
            <th>{{ __('admin.users-roles') }}</th>
            <td>{{ $main->role->name }}</td>
        </tr>
    </table>
@endsection