routes/web.php
<?php
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function () {
    Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@showLoginForm')->name('login');
        Route::post('login', 'LoginController@login');
        Route::post('logout', 'LoginController@logout')->name('logout');
        Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
        Route::post('register', 'RegisterController@register');
        Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
        Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
        Route::post('password/reset', 'ResetPasswordController@reset');
        Route::get('socialite/{provider}', 'AuthController@redirectToProvider');
        Route::get('socialite/{provider}/callback', 'AuthController@handleProviderCallback');
    });
    Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth', 'roles'], 'block' => ['null']], function () {
        Route::group(['roles' => ['User', 'Author', 'Moderator', 'Admin']], function () {
            Route::get('/', 'AdminController@index')->name('admin.index');
            Route::get('profile', 'ProfileController@index')->name('profile.index');
            Route::get('profile/{id}/edit', 'ProfileController@edit')->name('profile.edit');
            Route::put('profile/{id}/edit', 'ProfileController@updateedit');
            Route::get('profile/{id}/password', 'ProfileController@password')->name('profile.password');
            Route::put('profile/{id}/password', 'ProfileController@updatepassword');
            Route::delete('profile/{id}', 'ProfileController@destroy')->name('profile.destroy');
            Route::resource('urls', 'UrlController');
        });
        Route::group(['roles' => ['Admin']], function () {
            Route::resource('users', 'UserController');
            Route::get('roles', 'RoleController@index')->name('roles.index');
            Route::get('role/{id}', 'RoleController@show')->name('roles.show');
            Route::get('roles/{id}/edit', 'RoleController@edit')->name('roles.edit');
            Route::put('roles/{id}', 'RoleController@update')->name('roles.update');
            Route::get('settings', 'AdminController@settings')->name('admin.settings');
            Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('admin.logs');
        });
    });
    Route::namespace('Site')->group(function () {
        Route::get('/', 'SiteController@index')->name('site.index');
        Route::put('/', 'SiteController@submit');
        Route::get('anonymous/{id}', 'SiteController@anonymous')->name('site.anonymous')->where('id', '[\w\d\-\_]+');
        Route::get('url/{id}', 'SiteController@url')->name('site.url')->where('id', '[\w\d\-\_]+');
    });
});

app/Url.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Url extends Model
{
    protected $fillable = ['url_key', 'url_site', 'views', 'user_id', 'status'];
}

app/Http/Controllers/Admin/UrlController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Url;
use App\Http\Requests\Url as Request;
use Illuminate\Support\Facades\Auth;

class UrlController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $main = Url::where('user_id', Auth::user()->id)->get();
        return view('admin.urls.index', compact('main'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.urls.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Url::create([
            'url_site' => $request->url_site,
            'views' => 0,
            'user_id' => Auth::user()->id,
            'status' => $request->status,
        ]);
        return redirect()->route('urls.index')->with('success', __('admin.created-success'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (Url::where('user_id', Auth::user()->id)) {
            $main = Url::find($id);
            return view('admin.urls.show', compact('main'));
        } else
            abort(403);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (Url::where('user_id', Auth::user()->id)) {
            $main = Url::find($id);
            return view('admin.urls.edit', compact('main'));
        } else
            abort(403);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (Url::where('user_id', Auth::user()->id)) {
            Url::find($id)->update([
                'url_site' => $request->url_site,
                'status' => $request->status
            ]);
            return redirect()->route('urls.index')->with('success', __('admin.updated-success'));
        } else
            abort(403);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (Url::where('user_id', Auth::user()->id)) {
            Url::find($id)->delete();
            return redirect()->route('urls.index')->with('success', __('admin.information-deleted'));
        } else
            abort(403);
    }
}

resources/views/ru/admin/urls/create.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.create-urls'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('urls.store') }}" method="POST">
        @csrf

        <div class="form-group">
            <label>{{ __('admin.urls-url_site') }}</label>
            <input type="text" class="form-control" name="url_site" value="{{ old('url_site') }}"
                   placeholder="{{ __('admin.urls-enter-url_site') }}" required>
        </div>

        <fieldset disabled>
            <div class="form-group">
                <label>{{ __('admin.urls-views') }}</label>
                <input type="text" class="form-control" name="url_site" value="0" required>
            </div>
        </fieldset>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                <option value="1">{{ __('admin.enabled') }}</option>
                <option value="0">{{ __('admin.disabled') }}</option>
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.create') }}</button>
    </form>
@endsection

resources/views/ru/admin/urls/edit.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.edit-urls'))

@section('content')
    @include('admin.includes.title')
    @include('admin.includes.error')
    <form action="{{ route('urls.update',$main->id) }}" method="POST">
        @csrf
        @method('PUT')
        <fieldset disabled>
            <div class="form-group">
                <label>{{ __('admin.urls-url_key') }}</label>
                <input type="text" class="form-control" name="id" value="{{ url('/') .'/url/'.$main->id }}" required>
            </div>
        </fieldset>
        <div class="form-group">
            <label>{{ __('admin.urls-url_site') }}</label>
            <input type="text" class="form-control" name="url_site" value="{{ $main->url_site }}"
                   placeholder="{{ __('admin.urls-enter-url_site') }}" required>
        </div>

        <fieldset disabled>
            <div class="form-group">
                <label>{{ __('admin.urls-views') }}</label>
                <input type="text" class="form-control" name="views" value="{{ $main->views }}" required>
            </div>

            <div class="form-group">
                <label>{{ __('admin.created') }}</label>
                <input type="text" class="form-control" name="created" value="{{ $main->created_at }}" required>
            </div>
        </fieldset>

        <div class="form-group">
            <label>{{ __('admin.status') }}</label>
            <select class="form-control" name="status" required>
                @if($main->status)
                    <option value="1">{{ __('admin.enabled') }}</option>
                    <option value="0">{{ __('admin.disabled') }}</option>
                @else
                    <option value="0">{{ __('admin.disabled') }}</option>
                    <option value="1">{{ __('admin.enabled') }}</option>
                @endif
            </select>
        </div>

        <button class="btn btn-lg btn-original btn-block" type="submit">{{ __('admin.edit') }}</button>
    </form>
@endsection

resources/views/ru/admin/urls/index.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.urls'))

@section('content')
    <div class="row justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <div class="col-lg-9">
            <div class="d-flex">
                <h1 class="h2">@yield('title')</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="pull-right">
                <a class="btn btn-original" href="{{ route('urls.create') }}">{{ __('admin.create-urls') }}</a>
            </div>
        </div>
    </div>
    @include('admin.includes.success')
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered" style="width:100%">
            <thead>
            <tr>
                <th scope="col">{{ __('admin.urls-url_key') }}</th>
                <th scope="col">{{ __('admin.urls-url_site') }}</th>
                <th scope="col">{{ __('admin.urls-views') }}</th>
                <th scope="col">{{ __('admin.created') }}</th>
                <th scope="col">{{ __('admin.status') }}</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($main as $item)
                <tr>
                    <td scope="row">{{ route('site.url', $item->id) }}</td>
                    <td scope="row">{{ $item->url_site }}</td>
                    <td scope="row">{{ $item->views }}</td>
                    <td scope="row">{{ $item->created_at }}</td>
                    <td scope="row">
                        @if($item->status)
                            {{ __('admin.enabled') }}
                        @else
                            {{ __('admin.disabled') }}
                        @endif
                    </td>
                    <td scope="row">
                        <a href="{{ route('urls.show',$item->id) }}"><i class="far fa-eye"></i></a>
                        <a href="{{ route('urls.edit',$item->id) }}"><i class="fas fa-edit"></i></a>
                        <form action="{{ route('urls.destroy',$item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/ru/admin/urls/show.blade.php
@extends('admin.layouts.main')

@section('title',__('admin.show-urls'))

@section('content')
    @include('admin.includes.title')
    <ul class="nav mb-md-3">
        <li>
            <a href="{{ route('urls.index') }}" class="btn btn-dark">{{ __('admin.back') }}</a>
            <a href="{{ route('urls.edit', $main->id) }}" class="btn btn-primary">{{ __('admin.update') }}</a>
            <form action="{{ route('urls.destroy', $main->id) }}" method="POST">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger">{{ __('admin.delete') }}</button>
            </form>
        </li>
    </ul>
    <table class="table">
        <tr>
            <th>{{ __('admin.urls-url_key') }}</th>
            <td>{{ route('site.url', $main->id) }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.urls-url_site') }}</th>
            <td>{{ $main->url_site }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.urls-views') }}</th>
            <td>{{ $main->views }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.created') }}</th>
            <td>{{ $main->created_at }}</td>
        </tr>
        <tr>
            <th>{{ __('admin.status') }}</th>
            <td>
                @if($main->status)
                    {{ __('admin.enabled') }}
                @else
                    {{ __('admin.disabled') }}
                @endif
            </td>
        </tr>
    </table>
@endsection